services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    depends_on:
      db-migrate:
        condition: service_completed_successfully
  db-migrate:
    build:
      context: .
      target: deps
    restart: no
    environment:
      - DATABASE_URL=postgresql://postgres:Aa123456@db:5432/checklist-api
    command: sh -c "npx prisma db push"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.4
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=checklist-api
      - POSTGRES_PASSWORD=Aa123456
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
    name: checklist-api-data

